[package]
name = "osu-pp-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "lazer" }
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
